package li.kazu.java.dragtag.model;

public enum LanguageConstant {

	TITLE_DRAG,
	
	MAIN_BTN_SAVE_FILE_TOOLTIP,
	MAIN_BTN_RENAME_FILE_TOOLTIP,
	MAIN_BTN_CLOSE_FILE_TOOLTIP,
	MAIN_BTN_EXIT_TOOLTIP,
	
	MAIN_BTN_SAVE_FILE_TEXT,
	MAIN_BTN_RENAME_FILE_TEXT,
	MAIN_BTN_CLOSE_FILE_TEXT,
	MAIN_BTN_EXIT_TEXT,
	
	MAIN_BTN_SEARCH_ARTIST_TOOLTIP,
	MAIN_BTN_SEARCH_TITLE_TOOLTIP,
	MAIN_BTN_SEARCH_ALBUM_TOOLTIP,
	MAIN_BTN_SEARCH_ARTIST_AND_TITLE_TOOLTIP,
	MAIN_BTN_SEARCH_OTHER_TOOLTIP,
	
	MAIN_PNL_TAG_EDIT,
	MAIN_PNL_SEARCH_RESULT,
	MAIN_PNL_SEARCH_OPTIONS,
	MAIN_PNL_CONTROL,
	MAIN_PNL_FINGERPRINTING,
	
	MAIN_LBL_ARTIST,
	MAIN_LBL_TITLE,
	MAIN_LBL_ALBUM,
	MAIN_LBL_GENRE,
	MAIN_LBL_YEAR,
	MAIN_LBL_COVER,
	
	SETTINGS_LBL_OUTPUT_PATH,
	SETTINGS_LBL_OUTPUT_FORMAT,
	SETTINGS_LBL_SEARCH_LIMIT,
	
	SETTINGS_LBL_OUTPUT_PATH_DESC,
	SETTINGS_LBL_OUTPUT_FORMAT_DESC,
	SETTINGS_LBL_SEARCH_LIMIT_DESC,
	
	SETTINGS_PNL_OUTPUT,
	SETTINGS_PNL_SEARCH,
	
	TAB_SETTINGS,
	TAB_MAIN,
	
	ERR_MISSING_OUTPUT_PATH,
	ERR_MISSING_FILENAME_FORMAT,
	ERR_MISSING_SEARCH_LIMIT,
	ERR_INVALID_PATTERN,
	
}
